module AWS_CONFIG_VAR

  HOSTNAME=""
  AWS_ACCESS_KEY_ID=""
  AWS_SECRET_ACCESS_KEY=""
  AWS_ROOT_KEY=""
  AWS_DEF_AMI=""
  AWS_DEF_REG=""
  AWS_DEF_SG=""
  AWS_DEF_SUBNET=""
  AWS_DEF_KEYPAIR=""
end
